#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViewProject.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class ChangePassword : System.Web.Mvc.WebViewPage<LibraryViewProject.Models.ChangePasswordModel>
    {
        public ChangePassword()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "Change Password";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Change Password</h2>\r\n<p>\r\n    Use the form below to change your password" +
". \r\n</p>\r\n<p>\r\n    New passwords are required to be a minimum of ");

            
            #line 12 "..\..\Views\Account\ChangePassword.cshtml"
                                             Write(Membership.MinRequiredPasswordLength);

            
            #line default
            #line hidden
WriteLiteral(" characters in length.\r\n</p>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 323), Tuple.Create("\"", 377)
            
            #line 15 "..\..\Views\Account\ChangePassword.cshtml"
, Tuple.Create(Tuple.Create("", 329), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.validate.min.js")
            
            #line default
            #line hidden
, 329), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 420), Tuple.Create("\"", 486)
            
            #line 16 "..\..\Views\Account\ChangePassword.cshtml"
, Tuple.Create(Tuple.Create("", 426), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")
            
            #line default
            #line hidden
, 426), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n");

            
            #line 18 "..\..\Views\Account\ChangePassword.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\ChangePassword.cshtml"
Write(Html.ValidationSummary(true, "Password change was unsuccessful. Please correct the errors and try again."));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\ChangePassword.cshtml"
                                                                                                               

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
"\r\n            <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.PasswordFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.PasswordFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.PasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Change Password\"");

WriteLiteral(" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");

            
            #line 53 "..\..\Views\Account\ChangePassword.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
