#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViewProject.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");


            
            #line 4 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link href=\"");


            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
           Write(Url.Content("~/Content/Site.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"");


            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
            Write(Url.Content("~/Scripts/jquery-1.5.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n</head>\r\n<body>\r\n    <div class=\"page\">\r\n    " +
"    <div id=\"header\">\r\n            <div id=\"title\">\r\n                <h1>My MVC " +
"Application</h1>\r\n            </div>\r\n            <div id=\"logindisplay\">\r\n     " +
"           ");


            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LogOnPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div id=\"menucontainer\">\r\n                <ul i" +
"d=\"menu\">\r\n                    <li>");


            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");


            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <div id" +
"=\"main\">\r\n            ");


            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderSection("SomeTestSection", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div id=\"footer\">\r\n        </div>\r\n    </div>\r\n</body>\r" +
"\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
