#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViewProject.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");

            
            #line 4 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 77), Tuple.Create("\"", 118)
            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 84), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Site.css")
            
            #line default
            #line hidden
, 84), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 168), Tuple.Create("\"", 219)
            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 174), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery-1.5.1.min.js")
            
            #line default
            #line hidden
, 174), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"title\"");

WriteLiteral(">\r\n                <h1>My MVC Application</h1>\r\n            </div>\r\n            <" +
"div");

WriteLiteral(" id=\"logindisplay\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LogOnPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"menucontainer\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");

            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderSection("SomeTestSection", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
