#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViewProject.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LogOnPartial.cshtml")]
    public partial class LogOnPartial : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LogOnPartial()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_LogOnPartial.cshtml"
 if(Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("Welcome <strong>");

            
            #line 2 "..\..\Views\Shared\_LogOnPartial.cshtml"
                     Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>!\r\n    [ ");

            
            #line 3 "..\..\Views\Shared\_LogOnPartial.cshtml"
 Write(Html.ActionLink("Log Off", "LogOff", "Account"));

            
            #line default
            #line hidden
WriteLiteral(" ]");

WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_LogOnPartial.cshtml"
}
else {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("[ ");

            
            #line 6 "..\..\Views\Shared\_LogOnPartial.cshtml"
   Write(Html.ActionLink("Log On", "LogOn", "Account"));

            
            #line default
            #line hidden
WriteLiteral(" ]\r\n");

            
            #line 7 "..\..\Views\Shared\_LogOnPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
