#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationRazorGeneratorSeparateLibrary.Areas.Demo.Views.Demo
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Demo/Views/Demo/JsonReference.cshtml")]
    public class JsonReference : System.Web.Mvc.WebViewPage<MvcApplicationRazorGeneratorSeparateLibrary.Models.RegisterModel>
    {
        public JsonReference()
        {
        }
        public override void Execute()
        {

WriteLiteral("           \r\n");


            
            #line 3 "..\..\Areas\Demo\Views\Demo\JsonReference.cshtml"
  
    ViewBag.Title = "JsonReference";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>JsonReference</h2>\r\n\r\n<script type=\"text/javascript\">\r\n        jQuery[\'tabl" +
"e01GridData\'] = ");


            
            #line 10 "..\..\Areas\Demo\Views\Demo\JsonReference.cshtml"
                                Write(new HtmlString(Json.Encode(Model)));

            
            #line default
            #line hidden
WriteLiteral(";\r\n</script>");


        }
    }
}
#pragma warning restore 1591
